# -*- coding: utf-8 -*-
"""Copy of aiml_miniproject_Final_Day.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1puUqmudmlljqDfo6uSBW83MPjtmQNwLv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import KDTree
from geopy.distance import great_circle
import heapq
import joblib
import gradio as gr
import folium

df = pd.read_csv("/content/flood_risk_dataset_india.csv")

features = ['Water Level (m)', 'River Discharge (m³/s)', 'Elevation (m)']
data = df[features].dropna().copy()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(data)

inertias = []
for k in range(1, 8):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    inertias.append(kmeans.inertia_)

plt.plot(range(1, 8), inertias, 'bo-')
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method for Optimal K (Using 3 Features)")
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
data["cluster"] = kmeans.fit_predict(X_scaled)

cluster_severity = (
    data.groupby("cluster")
        .mean()
        .assign(score=lambda df: df['Water Level (m)']*0.5
                                 + df['River Discharge (m³/s)']*0.3
                                 - df['Elevation (m)']*0.2)
        .sort_values("score")
)

risk_labels_order = ['No', 'Low', 'Medium', 'High']
risk_map = {
    cid: label for cid, label in zip(cluster_severity.index, risk_labels_order)
}

data['risk_label'] = data['cluster'].map(risk_map)

df['risk_label'] = data['risk_label']

print(df[['Water Level (m)',
          'River Discharge (m³/s)',
          'Elevation (m)',
          'risk_label']].head())


df.to_csv("flood_risk_clustered.csv", index=False)


risk_colors = {'No': 'lightgreen', 'Low': 'skyblue',
               'Medium': 'orange', 'High': 'red'}

plt.figure(figsize=(9, 7))

for label, color in risk_colors.items():
    subset = df[df['risk_label'] == label]
    plt.scatter(subset['Longitude'], subset['Latitude'],
                label=label, color=color, s=15)

plt.legend()
plt.title("Flood Risk (Using Water Level + River Discharge + Elevation)")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.show()

"""This code demonstrates a complete machine learning workflow for **flood risk clustering and visualization** using **K-Means**.

**Explanation:**

1. **Data Loading and Preparation:**
   The dataset 'flood_risk_dataset_india.csv' is read into a DataFrame, focusing on three critical features — *Latitude*, *Longitude*, and *Water Level (m)*. Missing values are removed to ensure clean input for clustering.

2. **Feature Scaling:**
   Since K-Means is distance-based, the features are standardized using **StandardScaler** to bring all variables to a common scale, preventing bias from differing magnitudes.

3. **Optimal Cluster Selection (Elbow Method):**
   The code computes K-Means inertia for cluster counts from 1 to 7. Plotting these values reveals the “elbow point,” which indicates the optimal number of clusters — here determined as **k = 4**.

4. **Clustering:**
   K-Means is then applied with 'n_clusters=4' to group areas with similar geographic positions and water levels. Each data point receives a cluster label.

5. **Cluster Interpretation:**
   The mean water level of each cluster is computed to assess relative flood severity. Clusters are categorized into **‘No’, ‘Low’, ‘Medium’, and ‘High’** risk levels accordingly.

6. **Result Export and Visualization:**
   The enriched dataset (including cluster and risk labels) is saved as 'flood_clustered.csv'. A scatter plot then visualizes the clusters on a map-like plot, showing the spatial distribution of flood risk across regions.

Now, for predicting the risk of any new coordinates, we have prepared a labelled data (no, medium, low and high risk).

We can train a classifier like random forest or logistic regression based on this data now.

"""

df = pd.read_csv("flood_risk_clustered.csv")

X = df[['River Discharge (m³/s)', 'Elevation (m)', 'Water Level (m)']]
y = df['risk_label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

import joblib
joblib.dump(model, "flood_risk_model.pkl")
print("Model saved as flood_risk_model.pkl")

"""This code builds a supervised learning model to predict flood risk levels based on geographical and water-level data. The dataset flood_clustered.csv, which already contains risk labels derived from clustering, is first imported and split into features (Latitude, Longitude, Water Level (m)) and the target variable (risk_label). The data is then divided into training and testing sets to enable model validation. A Logistic Regression classifier is trained on the training data to learn the relationship between location attributes and flood risk categories (No, Low, Medium, High). Model performance is evaluated using a confusion matrix and classification report, which provide detailed accuracy and class-wise metrics. Finally, the trained model is serialized and saved as flood_risk_model.pkl using Joblib, allowing it to be deployed for predicting flood risk in new, unseen data points efficiently."""

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from shapely.geometry import Point
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
!pip install geopandas shapely fiona --quiet

data = pd.read_csv("/content/flood_risk_clustered.csv")

india_url = "https://raw.githubusercontent.com/datasets/geo-boundaries-world-110m/master/countries.geojson"
world = gpd.read_file(india_url)
india = world[world['name'] == 'India']

CENTER_ALLOCATION = {
    'Low': 50,
    'Medium': 50,
    'No': 50,
    'High': 50
}
TOTAL_CENTERS = sum(CENTER_ALLOCATION.values())
MIN_SEPARATION_DISTANCE = 0.0000001

final_centers_df = pd.DataFrame()
print("\n" + "-" * 50)
print(f"Targeting {TOTAL_CENTERS} centers with allocation: {CENTER_ALLOCATION}")

for risk_level, n_count in CENTER_ALLOCATION.items():
    zone_data = data[data['risk_label'] == risk_level].copy()

    zone_data = zone_data[
        (zone_data['Latitude'] >= 6.5) & (zone_data['Latitude'] <= 37.5) &
        (zone_data['Longitude'] >= 68.0) & (zone_data['Longitude'] <= 97.5)
    ]

    if len(zone_data) < n_count:
        print(f" Not enough points in {risk_level} zone, using {len(zone_data)} instead of {n_count}")
        n_count = len(zone_data)

    if n_count == 0:
        continue

    scaler = StandardScaler()
    zone_scaled = scaler.fit_transform(zone_data[['Latitude', 'Longitude']])

    kmeans = KMeans(n_clusters=n_count, random_state=42, n_init=10)
    kmeans.fit(zone_scaled)

    centers = scaler.inverse_transform(kmeans.cluster_centers_)

    from scipy.spatial import cKDTree
    tree = cKDTree(zone_data[['Latitude', 'Longitude']].values)
    nearest_idx = [tree.query(c)[1] for c in centers]
    centers = zone_data.iloc[nearest_idx][['Latitude', 'Longitude']].values

    temp = pd.DataFrame(centers, columns=['Latitude', 'Longitude'])
    temp['risk_level'] = risk_level
    final_centers_df = pd.concat([final_centers_df, temp], ignore_index=True)

print(f"Initial centers selected (before distance filtering): {len(final_centers_df)}")

selected_centers = []

for row in final_centers_df.itertuples(index=False):
    lat, lon, risk = row
    pt = Point(lon, lat)

    if not pt.within(india.geometry.squeeze()):
        continue

    too_close = False
    for sel in selected_centers:
        dist = np.linalg.norm(np.array([lat, lon]) - np.array(sel[:2]))
        if dist < MIN_SEPARATION_DISTANCE:
            too_close = True
            break

    if not too_close:
        selected_centers.append((lat, lon, risk))

centers_df = pd.DataFrame(selected_centers, columns=['Latitude', 'Longitude', 'risk_level'])

centers_df['Center_ID'] = [f"Center_{i+1}" for i in range(len(centers_df))]

print(f"Shelters: {len(centers_df)}")
print("Selected centers:")
print(centers_df)

plt.figure(figsize=(10, 8))
colors = {'Low': 'skyblue', 'Medium': 'orange', 'No': 'lightgreen', 'High': 'red'}

for lbl, color in colors.items():
    subset = data[data['risk_label'] == lbl]
    plt.scatter(subset['Longitude'], subset['Latitude'], c=color, s=15, alpha=0.3, label=f"{lbl} Risk")

plt.scatter(centers_df['Longitude'], centers_df['Latitude'], c='black', marker='X', s=70, label="Shelters", zorder=5)
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title(f"Strategic Rescue Center Locations (Total {len(centers_df)})")
plt.legend(fontsize='xx-small')
plt.grid(True)
plt.show()

centers_df.to_csv("/content/strategic_rescue_centers.csv", index=False)
print("Saved to strategic_rescue_centers.csv")

"""This code determines **strategic rescue center locations** based on the previously derived flood risk zones. It automates the process of optimally placing centers across areas of different flood severity while maintaining spatial separation.

**Explanation:**

1. **Setup and Configuration:**
The dictionary CENTER_ALLOCATION defines how many rescue centers should be placed in each risk zone — 15 in *Medium*, 10 in *Low*, and 18 in *High* risk areas. The total number of centers and a minimum separation distance (0.15 units) are also defined to prevent clustering of centers too close to one another.
2. **Zone-wise Center Selection:**
For each risk level, the script filters the corresponding data points. If fewer points exist than the allocated count, a warning is issued, and the maximum available points are used.

   * The latitude and longitude coordinates are scaled for uniformity.
   * **K-Means clustering** is then applied within each zone to identify optimal cluster centers — each representing a potential rescue location.
   * The centers are transformed back to their original coordinate scale and stored along with their risk level.
3. **Overlap Removal:**
To ensure efficient distribution, the code checks pairwise distances between proposed centers and removes any that are closer than the specified MIN_SEPARATION_DISTANCE. This step guarantees wider geographic coverage.
4. **Final Output and Visualization:**
Each selected center is assigned a unique Center_ID (e.g., *Center_1*, *Center_2*). A scatter plot then visualizes all data points color-coded by flood risk, with rescue centers marked as black “X” symbols for clear distinction.
5. **Result Export:**
The finalized list of centers, along with their coordinates and risk levels, is saved to **strategic_rescue_centers.csv**, providing a practical reference for emergency planning and on-ground rescue operations.

This code determines **strategic rescue center locations** based on the previously derived flood risk zones. It automates the process of optimally placing centers across areas of different flood severity while maintaining spatial separation.

**Explanation:**

1. **Setup and Configuration:**
   The dictionary CENTER_ALLOCATION defines how many rescue centers should be placed in each risk zone — 6 in *Medium*, 6 in *Low*, and 8 in *No* risk areas. The total number of centers and a minimum separation distance (0.5 units) are also defined to prevent clustering of centers too close to one another.

2. **Zone-wise Center Selection:**
   For each risk level, the script filters the corresponding data points. If fewer points exist than the allocated count, a warning is issued, and the maximum available points are used.

   * The latitude and longitude coordinates are scaled for uniformity.
   * **K-Means clustering** is then applied within each zone to identify optimal cluster centers — each representing a potential rescue location.
   * The centers are transformed back to their original coordinate scale and stored along with their risk level.

3. **Overlap Removal:**
   To ensure efficient distribution, the code checks pairwise distances between proposed centers and removes any that are closer than the specified MIN_SEPARATION_DISTANCE. This step guarantees wider geographic coverage.

4. **Final Output and Visualization:**
   Each selected center is assigned a unique Center_ID (e.g., *Center_1*, *Center_2*). A scatter plot visualizes all data points color-coded by flood risk, with rescue centers marked as black “X” symbols for clear distinction.

5. **Result Export:**
   The finalized list of centers, along with their coordinates and risk levels, is saved to **strategic_rescue_centers.csv**, providing a practical reference for emergency planning and on-ground rescue operations.
"""

import warnings
warnings.filterwarnings("ignore", message="X does not have valid feature names")

import math
import heapq
import joblib
import pandas as pd
import numpy as np
from geopy.distance import great_circle
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KDTree
import folium
import gradio as gr
flood_csv_path = "/content/flood_risk_clustered.csv"
centers_csv_path = "/content/strategic_rescue_centers.csv"
risk_model_path = "/content/flood_risk_model.pkl"
fleet_model_path = "/content/fleet_model.pkl"

flood_df = pd.read_csv(flood_csv_path)
centers_df = pd.read_csv(centers_csv_path)

if 'capacity_fleets' not in centers_df.columns:
    centers_df['capacity_fleets'] = centers_df['risk_level'].map({
        'High': 25, 'Medium': 18, 'Low': 12, 'No': 8
    }).fillna(10).astype(int)

risk_model_obj = joblib.load(risk_model_path)
if isinstance(risk_model_obj, (tuple, list)):
    risk_model, label_encoder = risk_model_obj[0], risk_model_obj[1]
    has_label_encoder = True
else:
    risk_model = risk_model_obj
    label_encoder = None
    has_label_encoder = False

try:
    fleet_model = joblib.load(fleet_model_path)
    fleet_model_loaded = True
except Exception:
    fleet_model_loaded = False

if 'Fleet_Resources' not in flood_df.columns:
    def calculate_fleets(row):
        base = 2.0
        water_factor = (row.get('Water Level (m)', 0.0)) * 1.8
        discharge_factor = (row.get('River Discharge (m³/s)', 0.0)) * 0.01
        pop_factor = (row.get('Population Density', 0.0)) * 0.002
        flood_history_factor = (row.get('Historical Floods', 0.0)) * 0.5
        elevation_factor = max(0.0, (200.0 - row.get('Elevation (m)', 200.0)) * 0.02)
        rainfall_factor = (row.get('Rainfall (mm)', 0.0)) * 0.03
        fleets = base + water_factor + discharge_factor + pop_factor + flood_history_factor + elevation_factor + rainfall_factor
        return int(max(1, round(fleets)))
    flood_df['Fleet_Resources'] = flood_df.apply(calculate_fleets, axis=1)

fleet_features = [
    'Rainfall (mm)',
    'Water Level (m)',
    'River Discharge (m³/s)',
    'Elevation (m)',
    'Population Density',
    'Historical Floods'
]

if not fleet_model_loaded:
    fleet_df = flood_df.dropna(subset=fleet_features + ['Fleet_Resources']).copy()
    Xf = fleet_df[fleet_features]
    yf = fleet_df['Fleet_Resources']
    fleet_model = RandomForestRegressor(n_estimators=200, random_state=42)
    fleet_model.fit(Xf, yf)
    joblib.dump(fleet_model, fleet_model_path)


RISK_MULTIPLIER = {'No': 0.6, 'Low': 1.0, 'Medium': 1.4, 'High': 1.9}
RISK_COST = {'No': 1, 'Low': 3, 'Medium': 6, 'High': 30}

def estimate_travel_time_km(distance_km, terrain='flood'):
    if terrain == 'flood':
        speed_kmh = 12.0
    else:
        speed_kmh = 40.0
    return round(distance_km / speed_kmh, 2)

def allocate_fleets_across_centers(centers_df_input, start_point, fleets_needed):
    df = centers_df_input.copy()
    df['dist'] = df.apply(lambda r: great_circle(start_point, (r["Latitude"], r["Longitude"])).km, axis=1)
    centers_sorted = df.sort_values('dist').copy()
    allocation = []
    remaining = int(fleets_needed)
    for _, row in centers_sorted.iterrows():
        if remaining <= 0:
            break
        can_send = int(min(row.get('capacity_fleets', 0), remaining))
        if can_send > 0:
            allocation.append({
                'Center_ID': row['Center_ID'],
                'risk': row['risk_level'],
                'distance_km': round(row['dist'], 2),
                'fleets': can_send
            })
        remaining -= can_send
    return allocation


def densify_corridor(df, start, goal, model, step_km=5.0, width_km=25.0):
    # Create evenly spaced samples along straight line + lateral offsets
    total_km = great_circle(start, goal).km
    n_steps = int(max(1, math.ceil(total_km / step_km)))
    extra = []
    lat1, lon1 = start
    lat2, lon2 = goal
    safe_wl = df['Water Level (m)'].median() if 'Water Level (m)' in df.columns else 0.0
    safe_dis = df['River Discharge (m³/s)'].median() if 'River Discharge (m³/s)' in df.columns else 0.0
    safe_elv = df['Elevation (m)'].median() if 'Elevation (m)' in df.columns else 0.0

    for i in range(1, n_steps):
        frac = i / n_steps
        ilat = lat1 + frac * (lat2 - lat1)
        ilon = lon1 + frac * (lon2 - lon1)
        extra.append((ilat, ilon, safe_wl, safe_dis, safe_elv))
        for side in [-1, 1]:
            dlat = (width_km / 111.0) * side
            extra.append((ilat + dlat, ilon, safe_wl, safe_dis, safe_elv))
            # small diagonal offset
            dlon = (width_km / 111.0) * 0.5 * side
            extra.append((ilat + dlat, ilon + dlon, safe_wl, safe_dis, safe_elv))

    if len(extra) == 0:
        return df.copy()

    extra_df = pd.DataFrame(extra, columns=[
        "Latitude", "Longitude",
        "Water Level (m)", "River Discharge (m³/s)", "Elevation (m)"
    ])

    # Predict labels: handle both numeric/string models
    Xpred = extra_df[[ 'River Discharge (m³/s)', 'Elevation (m)', 'Water Level (m)']]
    preds = model.predict(Xpred)
    if has_label_encoder:
        # numeric encoded -> convert to text
        extra_df['risk_label'] = label_encoder.inverse_transform(preds)
    else:
        extra_df['risk_label'] = preds

    return pd.concat([df.reset_index(drop=True), extra_df.reset_index(drop=True)], ignore_index=True)

# Neighbors with bigger radius to ensure connectivity
def neighbors(tree, coords, p, r_km=80):
    r_deg = r_km / 111.0
    idxs = tree.query_radius(np.array(p).reshape(1, -1), r=r_deg)[0]
    return [(float(coords[i][0]), float(coords[i][1])) for i in idxs]

def nearest(tree, coords, point):
    d, i = tree.query(np.array(point).reshape(1, -1), k=1)
    c = coords[i[0][0]]
    return (float(c[0]), float(c[1]))

def haversine(p1, p2):
    return great_circle(p1, p2).km

def risk_cost_point(df, coords, tree, point):
    d, i = tree.query(np.array(point).reshape(1, -1), k=1)
    label = df.iloc[i[0][0]]['risk_label']
    return RISK_COST.get(label, 6)

def a_star(tree, df, coords, start, goal, alpha=1.0, tol_km=0.2):
    # map start/goal to nearest graph nodes
    start_node = nearest(tree, coords, start)
    goal_node = nearest(tree, coords, goal)
    if start_node == goal_node:
        # nudge goal slightly to create a small path
        goal_node = (goal_node[0] + 0.0005, goal_node[1] + 0.0005)

    openh = [(0, start_node)]
    came = {}
    gscore = {start_node: 0}

    while openh:
        _, curr = heapq.heappop(openh)
        if haversine(curr, goal_node) <= tol_km:
            path = [curr]
            while curr in came:
                curr = came[curr]
                path.append(curr)
            return path[::-1]
        for nb in neighbors(tree, coords, curr, r_km=80):
            if nb == curr:
                continue
            d = haversine(curr, nb)
            cost = d + risk_cost_point(df, coords, tree, nb)
            ng = gscore[curr] + cost
            if nb not in gscore or ng < gscore[nb]:
                came[nb] = curr
                gscore[nb] = ng
                f = ng + haversine(nb, goal_node) + alpha * risk_cost_point(df, coords, tree, nb)
                heapq.heappush(openh, (f, nb))
    return None


def sos(lat, lon):
    if lat is None or lon is None:
        return ("Location not detected", "", "", "")

    start = (lat, lon)

    # nearest center
    centers_df['distance_km'] = centers_df.apply(
        lambda r: great_circle(start, (r['Latitude'], r['Longitude'])).km, axis=1
    )
    nearest_center = centers_df.loc[centers_df['distance_km'].idxmin()]
    goal = (float(nearest_center['Latitude']), float(nearest_center['Longitude']))
    dist = float(nearest_center['distance_km'])

    # nearest flood datapoint
    flood_df['sos_dist'] = flood_df.apply(
        lambda r: great_circle(start, (r['Latitude'], r['Longitude'])).km, axis=1
    )
    closest_data = flood_df.loc[flood_df['sos_dist'].idxmin()]

    # fleet prediction (use DataFrame with column names to avoid sklearn warning)
    fleet_input_df = pd.DataFrame([closest_data[fleet_features].values], columns=fleet_features)
    raw_fleets = int(round(fleet_model.predict(fleet_input_df)[0]))

    risk_level = str(closest_data['risk_label'])
    scaled_fleets = int(math.ceil(raw_fleets * RISK_MULTIPLIER.get(risk_level, 1.0)))

    # allocation
    allocation = allocate_fleets_across_centers(centers_df, start, scaled_fleets)
    if len(allocation) == 0:
        allocation_text = "No centers available for allocation."
        nearest_center_dist = dist
    else:
        nearest_center_dist = allocation[0]['distance_km']

    travel_time_hr = estimate_travel_time_km(nearest_center_dist)

    # densify and build KDTree
    flood_df2 = densify_corridor(flood_df, start, goal, risk_model, step_km=5.0, width_km=25.0)
    coords = flood_df2[['Latitude', 'Longitude']].to_numpy()
    tree = KDTree(coords, leaf_size=40)

    path = a_star(tree, flood_df2, coords, start, goal, alpha=2.0, tol_km=0.5)

    # safety tips
    tips = "\n".join([f"- {t}" for t in (safety_tips.get(risk_level, safety_tips.get('Medium')))])

    # build map
    m = folium.Map(location=[lat, lon], zoom_start=13)

    # User location
    folium.Marker(
        [lat, lon],
        popup="You (Emergency)",
        icon=folium.Icon(color="red")
    ).add_to(m)

    # Marker for every center
    for _, row in centers_df.iterrows():
        folium.Marker(
            [row['Latitude'], row['Longitude']],
            popup=f"{row['Center_ID']} ({row['risk_level']})",
            icon=folium.Icon(color="blue")
        ).add_to(m)

    # Draw SAFE ROUTES ONLY TO ALLOCATED CENTERS
    colors = ["blue", "green", "purple", "orange", "black"]
    color_i = 0

    for center in allocation:
        c_lat = float(centers_df.loc[centers_df['Center_ID'] == center['Center_ID'], 'Latitude'].values[0])
        c_lon = float(centers_df.loc[centers_df['Center_ID'] == center['Center_ID'], 'Longitude'].values[0])
        goal_c = (c_lat, c_lon)

        # Densify corridor for this center
        flood_df_c = densify_corridor(flood_df, start, goal_c, risk_model, step_km=5.0, width_km=25.0)
        coords_c = flood_df_c[['Latitude', 'Longitude']].to_numpy()
        tree_c = KDTree(coords_c, leaf_size=40)

        # Path
        path_c = a_star(tree_c, flood_df_c, coords_c, start, goal_c, alpha=2.0, tol_km=0.5)

        if path_c:
            clean_path = [[float(p[0]), float(p[1])] for p in path_c]
            folium.PolyLine(
                clean_path,
                color=colors[color_i % len(colors)],
                weight=5,
                opacity=0.85,
                tooltip=f"Route to {center['Center_ID']}"
            ).add_to(m)
        else:
            print(f"No path found for {center['Center_ID']}")

        color_i += 1

    map_html = m._repr_html_()


    # text output
    risk_text = f"Flood Risk Level: **{risk_level}**"
    rescue_text = "### Fleet Deployment Plan\n"
    rescue_text += f"Total Fleets Required: **{scaled_fleets}**\n"
    rescue_text += f"Risk Zone: **{risk_level}**\n"
    rescue_text += f"First-Center ETA: **{travel_time_hr} hours**\n\n"
    rescue_text += "### Allocation:\n"
    for item in allocation:
        rescue_text += f"- **{item['Center_ID']}** ({item['risk']}) → {item['fleets']} fleets (Distance: {item['distance_km']} km)\n"

    return risk_text, rescue_text, tips, map_html


safety_tips = {
    "High": [
        "Move to higher ground immediately.",
        "Avoid bridges and low-lying areas.",
        "Turn off electricity and gas supply.",
        "Keep emergency kit and documents safe."
    ],
    "Medium": [
        "Monitor alerts from authorities.",
        "Prepare emergency supplies and evacuation plan.",
        "Avoid unnecessary travel.",
        "Move valuables to upper floors."
    ],
    "Low": [
        "Stay informed through weather updates.",
        "Keep basic supplies ready.",
        "Avoid waterlogged areas.",
        "Assist elderly and children if needed."
    ],
    "No": [
        "Stay alert during heavy rainfall.",
        "Ensure drainage around your home is clear.",
        "Keep emergency contacts handy."
    ]
}

def _is_distress_text(text):
    distress_keywords = ["help", "please", "panic", "scared", "fear", "emergency", "save", "urgent", "danger", "sos"]
    text = (text or "").lower()
    return any(k in text for k in distress_keywords)


def _sanitize_history(history):
    if history is None:
        return []
    out = []
    for item in history:
        if isinstance(item, dict) and 'role' in item and 'content' in item:
            out.append(item)
        elif isinstance(item, (list, tuple)) and len(item) == 2:
            role, content = item
            out.append({"role": role, "content": content})
        else:
            out.append({"role": "assistant", "content": str(item)})
    return out


def _last_assistant_message(history):
    for item in reversed(history or []):
        if item.get("role") == "assistant":
            return item.get("content", "")
    return ""


def chat_response(history, user_msg, lat_value, lon_value):
    history = _sanitize_history(history)
    user_msg = (user_msg or "").strip()
    user_lower = user_msg.lower()

    if user_msg == "":
        user_msg = ""
        user_lower = ""

    if user_msg:
        last = history[-1] if history else None
        if not (last and last.get("role") == "user" and last.get("content") == user_msg):
            history.append({"role": "user", "content": user_msg})

    assistant_reply = ""

    # If user is clearly in distress, immediate comforting message + try SOS if location available
    if _is_distress_text(user_msg):
        assistant_reply = (
            "💛 Hey — I know this feels frightening. You're not alone. "
            "Take a slow, deep breath with me: inhale… 2… 3… exhale… 2… 3…\n\n"
            "I will stay with you and guide every step."
        )
        # If location provided, run SOS and include summary
        if lat_value is not None and lon_value is not None:
            try:
                risk_text, rescue_text, tips, map_html = sos(lat_value, lon_value)
                # Keep reply concise in chat — map will appear in SOS panel if user presses SOS
                assistant_reply += "\n\n" + risk_text + "\n\n" + rescue_text.split('\n')[0]
                assistant_reply += "\n\n(Press the **SOS** button to view the full deployment plan and map.)"
            except Exception as e:
                assistant_reply += "\n\n(I attempted to compute SOS info but encountered an error.)"

    # If location missing, gently ask to get location
    elif lat_value is None or lon_value is None:
        assistant_reply = (
            "📍 I want to help you safely, but I need your location. "
            "Please press **Get My Location** — I will only use it to find nearby help. "
            "If you can't, tell me what's happening and I will guide you the best I can."
        )

    # Intent: check risk
    elif any(k in user_lower for k in ["risk", "flood", "check"]):
        assistant_reply = (
            f"🌧️ I see your location (Lat: {lat_value}, Lon: {lon_value}). "
            "Press **SOS** now and I'll compute your flood risk right away and show the safest route. "
            "Stay as calm as possible — keep your phone with you and don't move into floodwater."
        )

    # Intent: nearest rescue
    elif any(k in user_lower for k in ["rescue", "center", "nearest", "help nearby"]):
        # compute a light-weight nearest center summary
        try:
            centers_df["distance_km"] = centers_df.apply(
                lambda r: great_circle((lat_value, lon_value), (r["Latitude"], r["Longitude"])).km, axis=1
            )
            nc = centers_df.loc[centers_df["distance_km"].idxmin()]
            assistant_reply = (
                f"🚑 Nearest center: {nc['Center_ID']} ({nc.get('risk_level','')}) — {nc['distance_km']:.2f} km away. "
                "Press **SOS** to see route and deployment plan."
            )
        except Exception:
            assistant_reply = (
                "🚑 I'll find the nearest rescue center for you. Press **SOS** and I'll show where to go and how far it is. "
                "If you're alone, try to inform someone you trust about your location."
            )

    # Intent: route / map
    elif any(k in user_lower for k in ["route", "safe route", "map", "path"]):
        assistant_reply = (
            "🗺️ I will generate the safest route for you when you press **SOS**. "
            "Follow the route slowly and avoid walking through moving water. "
            "If at any point you feel unsafe, stop and call for help."
        )

    # Intent: safety tips
    elif any(k in user_lower for k in ["tip", "safety", "advice", "what to do"]):
        tips_list = safety_tips.get("High") if "High" in safety_tips else None
        if not tips_list:
            tips_list = [
                "Move to higher ground immediately",
                "Avoid bridges or flooded roads",
                "Do not walk through moving water",
                "Keep your phone charged and flashlight ready",
                "Listen to local authorities and rescue teams"
            ]
        assistant_reply = "🛟 Stay calm — here are the most important steps:\n" + "\n".join([f"- {t}" for t in tips_list])

    # Default friendly helper message with suggestions
    else:
        assistant_reply = (
            "💛 I'm here with you. I can:\n"
            "• Check your flood risk\n"
            "• Find nearest rescue center\n"
            "• Show the safest route\n"
            "• Give safety tips\n\n"
            "Try the quick questions below, or type how you're feeling and I'll respond."
        )

    # Prevent repeating same assistant reply twice in a row
    last_assistant = _last_assistant_message(history)
    if assistant_reply.strip() != last_assistant.strip():
        history.append({"role": "assistant", "content": assistant_reply})
    else:
        assistant_reply = last_assistant

    return history, assistant_reply


with gr.Blocks(theme=gr.themes.Soft()) as app:
    gr.Markdown("## 🌊 Flood Emergency Response System")
    gr.Markdown("Press **SOS** to get your location, nearest rescue center, safest route, and safety instructions.")

    # Inputs (same as before)
    lat = gr.Number(label="Latitude", interactive=True)
    lon = gr.Number(label="Longitude", interactive=True)

    get_loc_btn = gr.Button("📍 Get My Location")
    sos_btn = gr.Button("🚨 SOS - Get Help Now", variant="primary")

    # Outputs (same as before)
    risk_out = gr.Markdown()
    rescue_out = gr.Markdown()
    safety_out = gr.Markdown()
    map_out = gr.HTML()

    get_loc_btn.click(
        fn=None, inputs=None, outputs=[lat, lon],
        js="""
        async () => { return new Promise((resolve) => {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(
                    (pos) => resolve([pos.coords.latitude, pos.coords.longitude]),
                    () => resolve([null, null])
                );
            } else resolve([null, null]);
        });}
        """
    )

    # SOS button uses unified sos function
    sos_btn.click(fn=sos, inputs=[lat, lon], outputs=[risk_out, rescue_out, safety_out, map_out])

    gr.Markdown("### 🤖 AI Flood Assistant")
    chatbot = gr.Chatbot(label="AI Flood Assistant", type="messages")  # messages format

    # Quick suggestion radio (keeps interface minimal)
    suggested = gr.Radio(
        ["Check my flood risk", "Nearest rescue center", "Show safe route", "Safety tips"],
        label="Suggested quick questions",
        value=None
    )

    msg = gr.Textbox(label="Message", placeholder="Type your message or pick a suggestion...")

    # Invisible textbox to carry last assistant text for client-side TTS
    last_assistant_text = gr.Textbox(visible=False)

    # Wire up chatbot interactions:
    msg.submit(chat_response, inputs=[chatbot, msg, lat, lon], outputs=[chatbot, last_assistant_text])
    suggested.change(chat_response, inputs=[chatbot, suggested, lat, lon], outputs=[chatbot, last_assistant_text])

    # When last_assistant_text changes, run client-side JavaScript to speak it (browser TTS).
    speak_checkbox = gr.Checkbox(label="🔊 Speak responses (browser voice)", value=False)

    last_assistant_text.change(
        None,
        inputs=[last_assistant_text, speak_checkbox],
        outputs=[],
        js="""
        (texts_and_flag) => {
            const last_text = arguments[0];
            const speak_enabled = arguments[1];

            if (!speak_enabled) {
                return;
            }
            const msg = last_text || "";
            if (!msg || msg.trim() === "") return;

            try {
                const utter = new SpeechSynthesisUtterance(msg);
                utter.rate = 0.95;
                utter.pitch = 1.0;
                speechSynthesis.cancel();
                speechSynthesis.speak(utter);
            } catch (e) {
                console.log("TTS failed:", e);
            }
        }
        """
    )

# Launch
app.launch(share=True, debug=True)